version: '3'

services:
  kibana:
    image: kibana:7.4.0
    restart: always
    hostname: kibana
    privileged: true
    container_name: kibana
    ports:
      - "5601:5601"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    volumes:
      - ./kibana/data:/usr/share/kibana/data
      - ./kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml:Z
    networks:
      - elk
    depends_on:
      - elasticsearch_master
      - elasticsearch_worker_1
      - elasticsearch_worker_2
      - elasticsearch_worker_3

  logstash:
    image: logstash:7.4.0
    restart: always
    hostname: logstash
    privileged: true
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    volumes:
      - ./logstash/logs:/usr/share/logstash/logs:Z
      - ./logstash/data:/usr/share/logstash/data:Z
      - ./logstash/conf/logstash.yml:/usr/share/logstash/config/logstash.yml:Z
      - ./logstash/conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:Z
    networks:
      - elk
    depends_on:
      - elasticsearch_master
      - elasticsearch_worker_1
      - elasticsearch_worker_2
      - elasticsearch_worker_3
    environment:
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"

  elasticsearch_master:
    image: elasticsearch:7.4.0
    restart: always
    hostname: elasticsearch_master
    privileged: true
    container_name: elasticsearch_master
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    volumes:
      - ./elasticsearch/elasticsearch_master/logs:/usr/share/elasticsearch/logs:Z
      - ./elasticsearch/elasticsearch_master/data:/usr/share/elasticsearch/data:Z
      - ./elasticsearch/elasticsearch_master/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
    networks:
      elk:
        ipv4_address: 172.25.0.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  elasticsearch_worker_1:
    image: elasticsearch:7.4.0
    restart: always
    hostname: elasticsearch_worker_1
    privileged: true
    container_name: elasticsearch_worker_1
    ports:
      - "9201:9200"
      - "9301:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    volumes:
      - ./elasticsearch/elasticsearch_worker_1/logs:/usr/share/elasticsearch/logs:Z
      - ./elasticsearch/elasticsearch_worker_1/data:/usr/share/elasticsearch/data:Z
      - ./elasticsearch/elasticsearch_worker_1/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
    networks:
      - elk
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  elasticsearch_worker_2:
    image: elasticsearch:7.4.0
    restart: always
    hostname: elasticsearch_worker_2
    privileged: true
    container_name: elasticsearch_worker_2
    ports:
      - "9202:9200"
      - "9302:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    volumes:
      - ./elasticsearch/elasticsearch_worker_2/logs:/usr/share/elasticsearch/logs:Z
      - ./elasticsearch/elasticsearch_worker_2/data:/usr/share/elasticsearch/data:Z
      - ./elasticsearch/elasticsearch_worker_2/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
    networks:
      - elk
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  elasticsearch_worker_3:
    image: elasticsearch:7.4.0
    restart: always
    hostname: elasticsearch_worker_3
    privileged: true
    container_name: elasticsearch_worker_3
    ports:
      - "9203:9200"
      - "9303:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    volumes:
      - ./elasticsearch/elasticsearch_worker_3/logs:/usr/share/elasticsearch/logs:Z
      - ./elasticsearch/elasticsearch_worker_3/data:/usr/share/elasticsearch/data:Z
      - ./elasticsearch/elasticsearch_worker_3/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
    networks:
      - elk
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

networks:
  elk:
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/16"
